# Generated by Django 6.0.4 on 2026-04-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together={('merchant', 'idempotency_key')},
        ),
    ]
